### ISSUE TITLE
Can you please tell me how botium can be used to train the my utteracances for which my chatbot is not able to find proper intent or how can use botium for intent resolution 

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-bindings#106]
I am using watson assistant. and I want to train my utterances using automation. Can botium provide any solution for it?

**Comment by radhabasida** [comment]
I am using watson assistant. and I want to train my utterances using automation. Can botium provide any solution for it?

**Comment by codeforequity-at** [comment]
The process usually is to compose a test set containing all the utterances you want your Watson to train, then send all of them to Watson with Botium, and you evaluate the result. The training itself is done in Watson, on the _Improvement_ tab. And then repeat until all utterances are resolved.

You typically don't have to write full convo files as test cases, you can just write the utterances files and use the "Expand Utterances to Conversations" option in Botium Box, or the "expandutterances" argument to Botium CLI.

![image](https://user-images.githubusercontent.com/26287439/55468199-2197d500-5603-11e9-9182-9465335a7d88.png)

https://chatbotsmagazine.com/10-minutes-codeless-test-automation-for-ibm-watson-chatbots-d71eac9626d7
