### ISSUE TITLE
WATSONCONVERSATION_URL not working

### ISSUE THREAD

**Issue by behruz932-13** [codeforequity-at/botium-bindings#110]
In old versions. WATSONCONVERSATION_URL is working. It can be define in testmybot.json file. Now it renamed to botium.json but this FEATURE not exist

**Comment by codeforequity-at** [comment]
Watson Conversation Service has been renamed to Watson Assistant some time ago, so we decided to rename the capabilities as well. Please see the connector documentation: https://github.com/codeforequity-at/botium-connector-watson

**Comment by behruz932-13** [comment]
In this documentation https://github.com/codeforequity-at/botium-connector-watson, I see "WATSON_APIKEY", but it's not what I want (WATSONCONVERSATION_URL). Recently I used url of our server and from our server it connected to watson. We used this approach because we used several workspaces and our server can switch from one to next one workspace, and other fuctionality. Can you say some way, how to use old version? Or where should I define URL of our server?

**Comment by behruz932-13** [comment]
@codeforequity-at Please help to solve my issue?

**Comment by codeforequity-at** [comment]
Please read the link I provided. The capabilities have been renamed. The connector supports Assistant SDK V1 (the old one with workspaces) and V2 (the new one with assistants and skills).
