### ISSUE TITLE
Is it possible to use old version's feature (WATSONCONVERSATION_URL)?

### ISSUE THREAD

**Issue by behruz932-13** [codeforequity-at/botium-bindings#111]
In documentation https://github.com/codeforequity-at/botium-connector-watson, I see "WATSON_APIKEY", but it's not what I want (WATSONCONVERSATION_URL). Recently I used url of our server and from our server it connected to watson. We used this approach because we used several workspaces and our server can switch from one to next one, and other fuctionality. Can you say some way, how to use old version? Or where should I define URL of our server?

**Comment by codeforequity-at** [comment]
See #110
