### ISSUE TITLE
How to close a botium-bindings simulation session gracefully?

### ISSUE THREAD

**Issue by jpiduru** [codeforequity-at/botium-bindings#117]
when i am running a test with shouldfail convo.txt test is failed successfully but next time when i try and run a new test the old simulation session is still there and stuck in the Intent failing the new test. Instead is there a way to close the session gracefully with fluent driver after the test run is completed? 

I am using Alexa SMAPI simulator connector

For example my convo is 

#me 
Hi

bot
Hello

me
do something wrong ( i am stuck in this intent would like to end this session)

**Comment by codeforequity-at** [comment]
currently not supported in botium. would be useful - maybe you are interested in contributing a pull request ? otherwise will schedule for the december release.

**Comment by jpiduru** [comment]
Thank you. Could you point me where the driver() code is located and its documentation?

Implementation of BotDriver() document. I have installed selenium connector am not sure if it is required as i am using Alexa smapi connector for simulation.

First would be interested in understanding the implementation. Do i implement it in botium-core/bindings?

**Comment by codeforequity-at** [comment]
you only have to install the connectors you are using. selenium is not required for alexa smapi.

There is not much developer docs available, here is a very short guide: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/58261505/Contribution+Guide+for+Botium+Core

but this kind of feature is clearly part of the Smapi connector, not of botium core or botium bindings. you can find the connector list with links to the Github repositories here: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360553/Botium+Connectors

Quick google search showed me that in the Alexa SMAPI docs (https://developer.amazon.com/de/docs/smapi/skill-simulation-api.html) there is a "session mode" which I guess could be useful. has to be part of the SMAPI calls from botium.

**Comment by jpiduru** [comment]
reg the "session mode" , do i have to add this as a capability in the botium-connector?
I looked thru the botium-smapi repo and didn't find the simulation related code

https://github.com/codeforequity-at/botium-connector-alexa-smapi

Can you point me where the smapi simulation call is made with input.content & device.locale? 

Thanks!

**Comment by codeforequity-at** [comment]
there is already a bigger update in the loop for the latest alexa api
version. its in a feature branch and as far as i can tell this is already
part of it. it also includes an initialization wizard cli now, and it
requires setting up your own security profile (the wizard will give
instructions).

would be cool if you checkout this feature branch and tell if it does what
you require

jpiduru <notifications@github.com> schrieb am So., 29. Dez. 2019, 17:57:

**Comment by jpiduru** [comment]
Perfect! yeah , i was looking for that session mode.

https://github.com/codeforequity-at/botium-connector-alexa-smapi/blob/feature/BOT-992-connector-smapi-activate-session/src/SmapiClient.js#L80
Can you tell when is it scheduled for a release?

**Comment by codeforequity-at** [comment]
january release

**Comment by jpiduru** [comment]
Just checking Is this feature released? does current botium bingings version has it?

**Comment by codeforequity-at** [comment]
yes
