### ISSUE TITLE
 botium-core-BotDriver BotDriver Build error: Error: ALEXA_SMAPI_REFRESHTOKEN capability required 

### ISSUE THREAD

**Issue by jpiduru** [codeforequity-at/botium-bindings#121]
I am using botium-bindings and botium connetor alexa-smapi for the alexa skill and having this error. Can you help how to generate value for   ALEXA_SMAPI_REFRESHTOKEN?

botium.json
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "netnodeweb",
      "CONTAINERMODE": "alexa-smapi",
      "ALEXA_SMAPI_API": "simulation",
      "ALEXA_SMAPI_SKILLID": "amzn1.ask.skill.xxxxxxxxxxxxxxxxxxxxxxx",
      "ALEXA_SMAPI_LOCALE": "en-US",
      "ALEXA_SMAPI_REFRESHTOKEN":"WHAT WOULD BE THE VALUE HERE????",
      "SCRIPTING_ENABLE_MEMORY":true
    },
    "Sources": {},
    "Envs": {}
  }
}

Error log - 

mocha spec

  botium-core-BotDriver Loaded Botium configuration file ./botium.json +0ms
  botium-core-BotDriver Build - Botium Core Version: 1.9.12 +4ms
  botium-core-BotDriver Build - Capabilites: { PROJECTNAME: 'skynetnodeweb',
  botium-core-BotDriver   TESTSESSIONNAME: 'Botium Test Session',
  botium-core-BotDriver   TEMPDIR: 'botiumwork',
  botium-core-BotDriver   CLEANUPTEMPDIR: true,
  botium-core-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-core-BotDriver   SIMULATE_WRITING_SPEED: false,
  botium-core-BotDriver   SIMPLEREST_PING_RETRIES: 6,
  botium-core-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_PING_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_PING_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_STOP_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_STOP_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_POLL_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_POLL_INTERVAL: 1000,
  botium-core-BotDriver   SIMPLEREST_POLL_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_METHOD: 'GET',
  botium-core-BotDriver   SIMPLEREST_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_EXTRA_OPTIONS: {},
  botium-core-BotDriver   SIMPLEREST_STRICT_SSL: true,
  botium-core-BotDriver   SIMPLEREST_INBOUND_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_CONTEXT_MERGE_OR_REPLACE: 'MERGE',
  botium-core-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-core-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  botium-core-BotDriver   SCRIPTING_XLSX_HASHEADERS: true,
  botium-core-BotDriver   SCRIPTING_CSV_SKIP_HEADER: true,
  botium-core-BotDriver   SCRIPTING_CSV_QUOTE: '"',
  botium-core-BotDriver   SCRIPTING_CSV_ESCAPE: '"',
  botium-core-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-core-BotDriver   SCRIPTING_ENABLE_MEMORY: true,
  botium-core-BotDriver   SCRIPTING_ENABLE_MULTIPLE_ASSERT_ERRORS: false,
  botium-core-BotDriver   SCRIPTING_MATCHING_MODE: 'wildcardIgnoreCase',
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_NAMING_MODE: 'justLineTag',
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_NAMING_UTTERANCE_MAX: '16',
  botium-core-BotDriver   SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
  botium-core-BotDriver   ASSERTERS: [],
  botium-core-BotDriver   LOGIC_HOOKS:
  botium-core-BotDriver    [ { ref: 'INLINEHOOK', src: [Function: InlineHook], global: true } ],
  botium-core-BotDriver   USER_INPUTS: [],
  botium-core-BotDriver   SECURITY_ALLOW_UNSAFE: true,
  botium-core-BotDriver   CONTAINERMODE: 'alexa-smapi',
  botium-core-BotDriver   ALEXA_SMAPI_API: 'simulation',
  botium-core-BotDriver   ALEXA_SMAPI_SKILLID: 'amzn1.ask.skill.f956c118-9043-4a52-a7a1-263d6d944a0e',
  botium-core-BotDriver   ALEXA_SMAPI_LOCALE: 'en-US' } +2ms
  botium-core-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-core-BotDriver   GITPATH: 'git',
  botium-core-BotDriver   GITBRANCH: 'master',
  botium-core-BotDriver   GITDIR: '.' } +10ms
  botium-core-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
  ✓ launch test case with text file
  botium-connector-PluginConnectorContainer-helper Botium plugin botium-connector-alexa-smapi loaded. Plugin version is 0.0.12 +0ms
  botium-connector-alexa-smapi Validate called +0ms
  botium-core-BotDriver BotDriver Build error: Error: ALEXA_SMAPI_REFRESHTOKEN capability required +481ms
ERROR:  Error: ALEXA_SMAPI_REFRESHTOKEN capability required
    at BotiumConnectorAlexaSmapi.Validate (/Users/xxxxx/xxxxx-ws/xxxxx/node_modules/botium-connector-alexa-smapi/dist/botium-connector-alexa-smapi-cjs.js:322:68)
    at PluginConnectorContainer.Validate (/Users/jpiduru/xxxxxx-ws/xxxxx/node_modules/botium-core/src/containers/PluginConnectorContainer.js:32:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by codeforequity-at** [comment]
See https://github.com/codeforequity-at/botium-connector-alexa-smapi
