### ISSUE TITLE
Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test

### ISSUE THREAD

**Issue by jpiduru** [codeforequity-at/botium-bindings#122]
test steps  are  successful however as given below in the log i am getting the Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test and it is failing the test. How to fix this error?

My spec file has

const bb = require('botium-bindings')
bb.helper.mocha().setupMochaTestSuite()

============log
botium-connector-BaseContainer _RunCustomHook onUserSays finished +6s
  botium-connector-alexa-smapi UserSays called +6s
  botium-connector-alexa-smapi Simulation created for simulation id 801158c2-d95b-4abb-b512-54d6ae20db9f, polling for response ... +258ms
  botium-connector-alexa-smapi Simulation got response: {"id":"801158c2-d95b-4abb-b512-54d6ae20db9f","status":"IN_PROGRESS"} +0ms
    1) test case for checking balance
  botium-connector-BaseContainer _RunCustomHook onStop finished +2s
  botium-connector-alexa-smapi Stop called +2s
  botium-connector-alexa-smapi Clean called +1ms
  botium-connector-BaseContainer _RunCustomHook onClean finished +1ms
  botium-connector-BaseContainer Cleanup rimrafing temp dir /Users/xxxx/netnodeweb-ws/netnodeweb/botiumwork/netnodeweb 20201022 153946 FxUqA +0ms

  0 passing (1m)
  1 failing

  1) netnodeweb test case for xxxxxxxx balance:
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netnodeweb@1.10.0 mocha: `mocha spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netnodeweb@1.10.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxx/.npm/_logs/2020-10-22T20_40_47_234Z-debug.log

**Comment by codeforequity-at** [comment]
Try it with:

    bb.helper.mocha().setupMochaTestSuite({ timeout: 120000 })

**Comment by jpiduru** [comment]
thank you that did it...
