### ISSUE TITLE
Unable to validate the bot response through botium for directline3 containermode for authenticated Microsoft chatbot

### ISSUE THREAD

**Issue by KBANDANA** [codeforequity-at/botium-bindings#126]
Echo is produced from Microsoft chatbot, when automated through Botium.  

Please find the below request and response send and received through botium:-

#me
hi

#bot                                              
hi
#bot                                            
reply of hi from bot 

Note:- Every time bot is producing the echo then answer is given.

Please find the below json file:-
{
"botium": {
"Capabilities": {
"PROJECTNAME": "bot",
"CONTAINERMODE": "directline3",
"DIRECTLINE3_SECRET": "XXXXXXXXXXXXXXXXX",
"DIRECTLINE3_ACTIVITY_TEMPLATE": {
"from":{
"name":"XXXX@domain.com",
"id":"XXXX@domain.com"
},
"type": "message"
}
}
}
}

Please let me know if there is any connecter for this or do I need to add something else for the authenticated Microsoft chatbot deployed in teams channel. Please suggest how to automate this ?

**Comment by codeforequity-at** [comment]
I consider this to be a bug:

* The activity template contains the user id
* Botium doesnt recognize this and then qualifies every outbound message as inbound message as well, leading to an echo

You can try to remove the "from" section of the DIRECTLINE3_ACTIVITY_TEMPLATE and let Botium fill this itself, but if your tests rely on a given value there then this will not really help.

**Comment by KBANDANA** [comment]
Thanks for your response.
I have tried to remove the id from the botium.json file from DIRECTLINE3_ACTIVITY_TEMPLATE ("id":"[XXXX@domain.com](mailto:XXXX@domain.com)). Now its not producing the echo.

**Comment by bandanakumari92** [comment]
@codeforequity-at  Please help to update on this issue.

**Comment by codeforequity-at** [comment]
We will fix this, but the mentioned workaround is fine as well

**Comment by codeforequity-at** [comment]
Fixed https://github.com/codeforequity-at/botium-connector-directline3/commit/9cc819f580db0af15fe57bc1062145bf4cd2442f
