### ISSUE TITLE
How to send the response for the adaptive card for MS chatbot for directline containermode

### ISSUE THREAD

**Issue by KBANDANA** [codeforequity-at/botium-bindings#127]
Hi Team,

I want to send the response for the adaptive card. Where I want to send the text for two fields and want to click on submit button.
How to achieve this. What is the flow of the convo file. Is there any connector is required.

where bot is replying in below way:-
Please provide all required details 
CARD(Please provide all required details) 
BUTTON(Submit | {"action":"Submit"}) 
BUTTON(Cancel | {"action":"Cancel"}) 
FORM(summary | Title) 
FORM(description | Description) 
FORM(priority | How urgent is your need?)

**Comment by bandanakumari92** [comment]
@codeforequity-at  Please help to update on the issue.

**Comment by codeforequity-at** [comment]
Here is an example how to set form values and submit the form: https://github.com/codeforequity-at/botium-connector-directline3/blob/master/samples/convo/spec/convo/form.convo.txt
